## datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springBoot?characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
          hibernate:
            dialect : org.hibernate.dialect.MySQL5Dialect
